name: Test
on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
      - develop
      - main

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Habits Install
        run: make habits/install

      - name: Habits Init
        run: make habits/init

      - name: Generate documentation
        run: make doc/build

      - name: Habits Check
        run: make habits/check

      - name: Uninstall Habits
        run: make habits/remove
